### ISSUE TITLE
Capture less formal conventions in generated schema 

### ISSUE THREAD

**Issue by radishmouse** [thunderbird/thunderbird-notifications#19]
It would be better if the schema generated by Pydantic could be used instead of the hand-written `schema.json`.

However, per [this discussion](https://github.com/thunderbird/thunderbird-notifications/pull/2#issuecomment-2157786392), it doesn't capture the less formal conventions that are included in the hand-written one.

~~This ticket is for investigating how we could improve the generated schema.~~

---

For this ticket:
- convert to use the [`Field` function](https://docs.pydantic.dev/latest/concepts/fields/)
- copy descriptions from the existing `schema.json`
- add as `description=` kwargs for corresponding `Field`

for example:
```python
from pydantic import Field
from pydantic.dataclasses import dataclass

@dataclass
class DataclassWithDescription:
   a_field: int = Field(description="descr text")
```

**Comment by radishmouse** [comment]
@freaktechnik Do you recall some of the conventions missing from the generated schema?

**Comment by freaktechnik** [comment]
https://github.com/thunderbird/thunderbird-notifications/blob/132a40012cc48eeb89211bae578f96d47c3bce17/schema.json#L16
https://github.com/thunderbird/thunderbird-notifications/blob/132a40012cc48eeb89211bae578f96d47c3bce17/schema.json#L21
specify the timezone - though for our parsing on the client side it's fine as long as it has a timezone...

---  

https://github.com/thunderbird/thunderbird-notifications/blob/132a40012cc48eeb89211bae578f96d47c3bce17/schema.json#L25
https://github.com/thunderbird/thunderbird-notifications/blob/132a40012cc48eeb89211bae578f96d47c3bce17/schema.json#L29
have qualifiers of text length (even if only very rough)

---  

https://github.com/thunderbird/thunderbird-notifications/blob/132a40012cc48eeb89211bae578f96d47c3bce17/schema.json#L42
describes which is the more urgent severity

**Comment by radishmouse** [comment]
Closed by https://github.com/thunderbird/thunderbird-notifications/pull/28
