### ISSUE TITLE
Conversion script should deal with missing properties in YAML files

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-notifications#23]
Right now, the YAML files appear to need every possible property specified, including empty lists for the include/exclude filters.

https://github.com/thunderbird/thunderbird-notifications/blob/main/yaml/example.yaml#L13

This makes the YAML difficult to edit and read, instead the conversion script should add empty values when outputting JSON for any properties that are required in the schema but aren't used in the YAML source.

**Comment by radishmouse** [comment]
Solved by using schema generated from pydantic model (#19). (PR coming shortly)

**Comment by radishmouse** [comment]
Closed by https://github.com/thunderbird/thunderbird-notifications/pull/28
