### ISSUE TITLE
Eliminate Go json validator

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-notifications#24]
We should be using Pydantic or a python generator here, this just adds extra and somewhat cumbersome steps at this point.

**Comment by radishmouse** [comment]
It seems that this library is the one to use: https://python-jsonschema.readthedocs.io/en/stable/

**Comment by radishmouse** [comment]
Closed by https://github.com/thunderbird/thunderbird-notifications/pull/28
