### ISSUE TITLE
Meta: Clean up workflow and schema modification

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-notifications#25]
This is a meta issue. Right now, editing the schema is a bit confusing. You need to edit the Python file AND the `schema.json` manually and make sure they line up, as `NotificationSchema.py` is used to validate the YAML whereas `schema.json` validates the JSON.

We need:
- [ ] #19 
- [x] #18
- [ ] #23 
- [ ] #27 
- [ ] #24

**Comment by radishmouse** [comment]
Closed by #28
