### ISSUE TITLE
Concat yaml files in a folder rather than parsing them into multiple output json files

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-notifications#27]
All notifications will go into one `notifications.json` file, but on the input side we probably want to concat yaml files together. That way, each time someone wants to add events, they PR a new file with a label appropriate to their events, and then they're just all concatted together for final output.

That should keep the files more readable and prevent a situation where somebody has to edit one big YAML file with 50 events in it.

Especially when you consider targeting and A/B testing will cause one conceptual "notification" to split into many different distinct events.

**Comment by radishmouse** [comment]
Closed by https://github.com/thunderbird/thunderbird-notifications/pull/28
