### ISSUE TITLE
Change schema to add "position" attribute to control in-app location of notification

### ISSUE THREAD

**Issue by tobypilling** [thunderbird/thunderbird-notifications#29]
We would like to have a new `position` attribute with possible values `botton-today-pane` and `bottom-spaces-toolbar`

**Comment by Sancus** [comment]
Is this optional or required? Which donation types does this affect? Probably not the donation_tab and donation_browser ones?

**Comment by tobypilling** [comment]
Yes it can be optional - if we don't get it, we default to the position that it is currently in now.
And yes, it impacts all others than donation_tab and donation_browser
