### ISSUE TITLE
Add json validation to yaml->json pipeline

### ISSUE THREAD

**Issue by malini** [thunderbird/thunderbird-notifications#3]
Chris proposed the idea of adding a json validator run against the yaml->json converted files to ensure they match our expected fields, and fail otherwise.

**Comment by radishmouse** [comment]
Here's what I did locally and should be easy(?) to run as a GH action:

Using a tool written in Go: https://github.com/santhosh-tekuri/jsonschema

```sh
jv schema.json example.json
```

No output means both the schema and the data file are valid.


For local dev only (not part of GH action), hot reloading on file change: https://github.com/eradman/entr:

```
ls *.json | entr -c jv schema.json example.json
```
