### ISSUE TITLE
Change schema to support targeting by user preference value

### ISSUE THREAD

**Issue by tobypilling** [thunderbird/thunderbird-notifications#31]
We would like to add the ability to target users based on a preference setting. The more flexible you can make it, the better.

If we want to keep it simple, we can just add an array called something like "prefOn" or "prefTrue" to both "include" and "exclude" collections and we can pass an array of values like ["extensions.webextensions.userScripts.enabled","mail.server.server2.is_gmail"]

The fancy version might look like this, where we could even specify regex values to target users with certain extensions or settings:

"preferences": [
            {
              "prefName": "mail.server.server\d+.name",
              "prefValue": "(?i)\bhotmail\b"
            },
            {
              "prefName": "extensions.webextensions.uuids",
              "prefValue": "(?i)\binbox-summary@example.com\b"
            }
          ]

**Comment by tobypilling** [comment]
Update: probably best in terms of privacy to stick with the first simpler option which just allows us to target based on boolean prefs that are set to true in app.

**Comment by tobypilling** [comment]
Update: please name the new key `pref_true`. If missing, we shall treat as false.

**Comment by Sancus** [comment]
> Update: please name the new key `pref_true`. If missing, we shall treat as false.

I'm confused how this is meant to work. So we have a list of prefs by name in the field `pref_true`. If they're in the "include" filter, that means if any of them are true, we display? And vice versa for exclude? What does "if missing we shall treat as false" mean?

**Comment by tobypilling** [comment]
Correct, this approach means there is no way to trigger a notification here based on pref being false. Think we can add pref_false too?

Sorry: "if missing we shall treat as false" --> If the pref key doesn't exist, we default to false and would not show

**Comment by Sancus** [comment]
Well, I don't recall the original intent here but there are a lot of booleans that amount to "this thing is on or off". If the idea is we can send a notification to people who are using a certain thing or not, it doesn't seem very useful to only be able to target true.

**Comment by tobypilling** [comment]
Ok thanks. To keep it easy and add that flexibility, it would be great to also add `pref_false` please.

The original intent was to give us the ability to reach more precise populations such as Gmail users etc so adding this pair will be great.
